apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2am-local-carbon-database-volume-claim
  namespace : wso2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50M
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2am-solr-indexed-data-volume-claim
  namespace : wso2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50M
  storageClassName: nfs-client